# permissions for end users to edit connections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: connection-editor-role
rules:
- apiGroups:
  - k8ssh.barpilot.io
  resources:
  - connections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8ssh.barpilot.io
  resources:
  - connections/status
  verbs:
  - get
